# Generated by Django 5.0.6 on 2024-06-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_rename_user_id_shipments_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='quentity',
            field=models.IntegerField(default=1),
        ),
    ]
