# Generated by Django 5.0.6 on 2024-06-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipments_admin_approved_alter_shipments_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipments',
            name='date_time',
        ),
    ]
